// GENERATED BY tool/generate_freezed_equatable.dart — DO NOT EDIT
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:equatable/equatable.dart';

part 'user.freezed.dart';
part 'user.g.dart';

@freezed
class User with _$User, EquatableMixin {
  const User._();
  const factory User({
    required List<DataItem> data,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  @override
  List<Object?> get props => [
    data,
  ];

}

@freezed
class DataItem with _$DataItem, EquatableMixin {
  const DataItem._();
  const factory DataItem({
    required int user_id,
    required String user_firstname,
    required String user_lastname,
    required String user_name,
    required String email,
    required String user_avatar,
    required dynamic user_status,
    required int room_id,
  }) = _DataItem;

  factory DataItem.fromJson(Map<String, dynamic> json) => _$DataItemFromJson(json);

  @override
  List<Object?> get props => [
    user_id,
    user_firstname,
    user_lastname,
    user_name,
    email,
    user_avatar,
    user_status,
    room_id,
  ];

}

