import 'dart:io';
import '../create_auto_files/path_constants.dart';
import 'path_constants.dart';

Future<void> main(List<String> args) async {
  if (args.isEmpty) {
    print('Usage: dart run locator_add_requried_data.dart <featureName> [isCubit]');
    return;
  }
  final featureName = args[0];
  final isCubit = args.length > 1 ? args[1] == 'true' : true;
  PathConstants().setData(featureName);
  await AddRequiredDataToSL(isCubit)();
}

class AddRequiredDataToSL {
  AddRequiredDataToSL(this.isCubit);
  final bool isCubit;

  Future<void> call() async {
    final file = File(PathConstants().singltonPath);
    String originalContent = '';
    if (!file.existsSync()) {
      originalContent = '''
/// this file is auto generated by the script, do not modify it manually.

import 'package:get_it/get_it.dart';
import '../api_helper/dio_helper.dart';
import '../base/base_local_repo.dart';

class AppLocator {
  AppLocator._();

  static final AppLocator _instance = AppLocator._();

  factory AppLocator() => _instance;

  final _sl = GetIt.instance;

  GetIt call()=>_sl;
  
  void init(){

  // ── Global Services ──────────────────────────────────────────────────────
    _sl.registerLazySingleton<BaseLocalRepo>(
      () => BaseLocalRepo(
        primarySessionId: DateTime.now().millisecondsSinceEpoch.toString(),
        secondarySessionId:( DateTime.now().millisecondsSinceEpoch+1111).toString(),
       ),
    );
    _sl.registerLazySingleton<DioHelper>(() => DioHelper.instance);
  }
}
      ''';
      await file.writeAsString(originalContent);
    }

    originalContent = await file.readAsString();
    late String controllerTxt, controllerFileName;
    if (isCubit) {
      // Cubit depends on BaseXxxService (abstraction) — GetIt resolves it via the
      // registered factory<BaseXxxService>() below, so _sl<BaseXxxService>() works.
      controllerTxt =
          '_sl.registerFactory(() => ${PathConstants().cubitName()}(_sl<${PathConstants().baseServiceName()}>()));';
      controllerFileName = PathConstants().cubitFileName();
    } else {
      controllerTxt =
          '_sl.registerLazySingleton<${PathConstants().baseServiceName()}>(() => ${PathConstants().notifierName()}(_sl<${PathConstants().baseServiceName()}>()));';
      controllerFileName = PathConstants().notifierFileName();
    }

    final importLines = originalContent
        .split('\n')
        .where((line) => line.trim().startsWith('import'))
        .toList();

    // Import both abstractions and concrete implementations
    originalContent = originalContent.replaceFirst(
      importLines.first,
      '''// ── ${PathConstants().name} ──────────────────────────────────────────────────────
import 'package:${PathConstants().projectName}/features/screens/${PathConstants().name}/data/repo/${PathConstants().baseRepoFileName()}';
import 'package:${PathConstants().projectName}/features/screens/${PathConstants().name}/data/repo/${PathConstants().remoteRepoFileName()}';
import 'package:${PathConstants().projectName}/features/screens/${PathConstants().name}/service/${PathConstants().baseServiceFileName()}';
import 'package:${PathConstants().projectName}/features/screens/${PathConstants().name}/service/${PathConstants().serviceFileName()}';
import 'package:${PathConstants().projectName}/features/screens/${PathConstants().name}/controller/$controllerFileName';
${importLines.first}''',
    );

    final initRegex = RegExp(r'void\s+init\s*\(\)\s*\{');
    if (originalContent.contains(initRegex)) {
      String hint = '///..................${PathConstants().name}.................///';
      if (originalContent.contains('$hint')) {
        print('⚠️ this Di is already registered.');
        return;
      }

      // ── Polymorphic registration ──────────────────────────────────────────
      // registerLazySingleton<Abstract>(() => Concrete(...))  
      // means GetIt will return the concrete class whenever any module asks
      // for the abstract type — full Dependency Inversion via the service locator.
      String additionalCode = '''    $hint
    // Repo layer: register the concrete impl under the abstract type
    _sl.registerLazySingleton<${PathConstants().baseRepoName()}>(() => ${PathConstants().repoName()}(_sl()));
    // Service layer: register the concrete impl under the abstract type
    _sl.registerLazySingleton<${PathConstants().baseServiceName()}>(() => ${PathConstants().serviceName()}(_sl<${PathConstants().baseRepoName()}>(), _sl()));
    // Controller layer: factory so a fresh cubit is created per BlocProvider
    $controllerTxt''';

      originalContent = originalContent.replaceFirst(
        initRegex,
        'void init(){\n$additionalCode\n',
      );
    }
    await file.writeAsString(originalContent);
    print('✅ DI registered for ${PathConstants().name} with polymorphic bindings.');
  }
}
