/// this file is auto generated by the script, do not modify it manually.

// ── main_screen ──────────────────────────────────────────────────────
import 'package:newf/features/screens/main_screen/data/repo/base_main_screen_repo.dart';
import 'package:newf/features/screens/main_screen/data/repo/main_screen_remote_repo.dart';
import 'package:newf/features/screens/main_screen/service/base_main_screen_service.dart';
import 'package:newf/features/screens/main_screen/service/main_screen_remote_service.dart';
import 'package:newf/features/screens/main_screen/controller/main_screen_cubit.dart';
import 'package:get_it/get_it.dart';

import '../api_helper/dio_helper.dart';
import '../base/base_local_repo.dart';

class AppLocator {
  AppLocator._();

  static final AppLocator _instance = AppLocator._();

  factory AppLocator() => _instance;

  final _sl = GetIt.instance;

  GetIt call()=>_sl;
  
  void init(){
    ///..................main_screen.................///
    // Repo layer: register the concrete impl under the abstract type
    _sl.registerLazySingleton<BaseMainScreenRepo>(() => MainScreenRemoteRepo(_sl()));
    // Service layer: register the concrete impl under the abstract type
    _sl.registerLazySingleton<BaseMainScreenService>(() => MainScreenRemoteService(_sl<BaseMainScreenRepo>(), _sl()));
    // Controller layer: factory so a fresh cubit is created per BlocProvider
    _sl.registerFactory(() => MainScreenCubit(_sl<BaseMainScreenService>()));


  // ── Global Services ──────────────────────────────────────────────────────
    _sl.registerLazySingleton<BaseLocalRepo>(
      () => BaseLocalRepo(
        primarySessionId: DateTime.now().millisecondsSinceEpoch.toString(),
        secondarySessionId:( DateTime.now().millisecondsSinceEpoch+1111).toString(),
       ),
    );
    _sl.registerLazySingleton<DioHelper>(() => DioHelper.instance);
  }
}
      